package UI.myControllers;

public enum Events {
    FOLD_BUTTON_1_CLICKED,
    FOLD_BUTTON_2_CLICKED,

    PLAY_BUTTON_1_CLICKED,
    PLAY_BUTTON_2_CLICKED,

    ANTE_BET_TEXT_FIELD_1_TEXT_CHANGED,
    ANTE_BET_TEXT_FIELD_2_TEXT_CHANGED,

    PAIR_PLUS_BET_TEXT_FILED_1_TEXT_CHANGED,
    PAIR_PLUS_BET_TEXT_FILED_2_TEXT_CHANGED
}
